# Condition C (PressLight): 1200s, rotating demand bag.
includes:
  - configs/tsc/presslight.yml
  - configs/tsc/demand_bag_1200_base.yml

world:
  demand_bag:
    - raw_data/grid4x4/demand_bag/train_00.rou.xml
    - raw_data/grid4x4/demand_bag/train_01.rou.xml
    - raw_data/grid4x4/demand_bag/train_02.rou.xml
    - raw_data/grid4x4/demand_bag/train_03.rou.xml
    - raw_data/grid4x4/demand_bag/train_04.rou.xml
    - raw_data/grid4x4/demand_bag/train_05.rou.xml
    - raw_data/grid4x4/demand_bag/train_06.rou.xml
    - raw_data/grid4x4/demand_bag/train_07.rou.xml
    - raw_data/grid4x4/demand_bag/train_08.rou.xml
    - raw_data/grid4x4/demand_bag/train_09.rou.xml
