#!/usr/bin/env bash
# Deprecated wrapper — M0 jobs are generated by extras/submit_m0_homo.sh
# (heredoc / _slurm_generated scripts with NO --export, matching realism_full).
#
# Use:
#   export MCS_LABEL=15288
#   ./extras/submit_m0_homo.sh smoke|all
echo "Use ./extras/submit_m0_homo.sh instead of sbatch'ing this file." >&2
exit 1
